default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci

development:
  <<: *default
  host: db
  database: rails8-test
  username: <%= ENV.fetch("RAILS_DATABASE_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD") { 'password1!' } %>
